### PR TITLE
Update README and added a md file for Learnings

### PR DESCRIPTION
**Pull request by utkarsh006**
- See changes [here](https://github.com/utkarsh006/Flow-Youtube/tree/changes)

### CODE REVIEW

**Comment by utkarsh006** [comment]
@ezatpanah Review this one too!

**Comment by ezatpanah** [comment]
sorry , i cannot merge anymore dm file , because it cause to change all the structure that i used for my readme file for youtube channel
thanks for your collaboration for the other one , exactly those one for youtube channel🙂

**Comment by utkarsh006** [comment]
@ezatpanah You can just add links to your channel. I've done changes so that your repo looks structured. Anyways, thanks for all your response on my PRs.

**Comment by ezatpanah** [comment]
Yes , you are right, but i want to keep same structure for whole my repo related to youtube channel , as you saw , the MR about other repo was accepted , again , thanks for your collaboration :)

**Pull request closed without merging**
